#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=200
STOP=200

start() {
        echo 'start arduino script'
        # nohup /root/start.js &
        /usr/bin/sudo -u root /root/start.js >> /tmp/start.log &
        # commands to launch application
}

stop() {
        echo stop
        # commands to kill application
}
